[package]
name = "tassist"
version = "0.1.0"
authors = ["Shelby Doolittle <shelby@shelbyd.com>"]

[dependencies]
bincode = "1.0.1"
failure = "0.1"
serde = "1.0"
serde_derive = "1.0"
structopt = "0.2"
